version: "3.9"
services:
  app:
    build: 
      context: ./app/
      dockerfile: Dockerfile
    container_name: curr-curr-app  
    image: curr-curr-app-image    
    ports:
      - "8888:8888"
  mongodb:
    build: 
      context: ./mongo/
      dockerfile: Dockerfile
    container_name: curr-curr-mongodb 
    image: curr-curr-mongodb-image      
